name: map_annotation
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1p
  - pip=21.2.4
  - python=3.10.4
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - attrs==21.4.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cycler==0.11.0
    - fiona==1.8.21
    - fonttools==4.33.3
    - geopandas==0.11.0
    - kiwisolver==1.4.3
    - matplotlib==3.5.2
    - munch==2.5.0
    - numpy==1.23.0
    - packaging==21.3
    - pandas==1.4.3
    - pillow==9.1.1
    - pyparsing==3.0.9
    - pyproj==3.3.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - shapely==1.8.2
    - six==1.16.0

